name: soranouta_app
description: "SoraNoUta Flutter game project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  sakiengine:
    path: ../../Engine
  soranouta_project:
    path: ./ProjectCode

dependency_overrides:
  flutter_steamworks:
    path: ../../third_party/flutter_steamworks_hotfix
  media_kit:
    path: ../../third_party/media_kit_hotfix
  media_kit_video:
    path: ../../third_party/media_kit_video_hotfix
  media_kit_libs_android_video:
    path: ../../third_party/media_kit_libs_android_video_hotfix
  media_kit_libs_ios_video:
    path: ../../third_party/media_kit_libs_ios_video_hotfix
  media_kit_libs_macos_video:
    path: ../../third_party/media_kit_libs_macos_video_hotfix
  media_kit_libs_windows_video:
    path: ../../third_party/media_kit_libs_windows_video_hotfix
  media_kit_libs_linux:
    path: ../../third_party/media_kit_libs_linux_hotfix

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - default_game.txt
    - Assets/
    - Assets/fonts/
    - Assets/gui/
    - Assets/images/
    - Assets/images/backgrounds/
    - Assets/images/cg/
    - Assets/images/cg/cg_cp0_1/
    - Assets/images/cg/cg_cp0_q2/
    - Assets/images/cg/cg_cp1_1/
    - Assets/images/cg/cg_cp1_2/
    - Assets/images/cg/cg_cp1_3/
    - Assets/images/cg/cg_cp1_5/
    - Assets/images/cg/cg_cp1_ls/
    - Assets/images/cg/cg_cp2_pond/
    - Assets/images/cg/cg_dog/
    - Assets/images/cg/cg_tree/
    - Assets/images/cg/cgmoto/
    - Assets/images/cg/shincg10/
    - Assets/images/cg/shincg11/
    - Assets/images/cg/shincg3/
    - Assets/images/cg/shincg4/
    - Assets/images/cg/shincg5/
    - Assets/images/cg/shincg6/
    - Assets/images/cg/shincg7/
    - Assets/images/cg/shincg9/
    - Assets/images/cg/shincg9_embrace/
    - Assets/images/characters/
    - Assets/images/characters/story1/
    - Assets/images/characters/story1/emoji/
    - Assets/images/characters/story1/pose/
    - Assets/images/characters/story2/
    - Assets/images/characters/story2/emoji/
    - Assets/images/characters/story2/pose/
    - Assets/images/items/
    - Assets/movies/
    - Assets/music/
    - Assets/sound/
    - Assets/stickers/
    - Assets/voice/
    - Assets/voice/cp0/
    - Assets/voice/cp1/
    - GameScript/
    - GameScript/configs/
    - GameScript/labels/
    - GameScript/台本/
    - GameScript/台本/第一章/
    - GameScript/台本/第零章/
    - .saki_cache/game.sakipak
  fonts:
    - family: SourceHanSansCN
      fonts:
        - asset: Assets/fonts/SourceHanSansCN-Bold.ttf
    - family: ChillJinshuSongPro_Soft
      fonts:
        - asset: Assets/fonts/ChillJinshuSongPro_Soft.otf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  web:
    generate: true
    image_path: "icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "icon.png"
  macos:
    generate: true
    image_path: "icon.png"
